### ISSUE TITLE
ONNX, Tensorrt Core Dumped

### ISSUE THREAD

**Issue by oscarfossey** [JunkyByte/easy_ViTPose#6] opened 2023-06-09 16:25 UTC
Hello, thank you very much for the great repo! Very helpful!
I work with a gpu with 8Go of V-RAM. When I load the torch models everything works well however when I try to load onnx and tensorrt models (for vitpose and for yolov5s), I got OOM and then Core dumped. Do you know how much more VRAM onnx and tensorrt are using?

**Comment by JunkyByte** [comment] 2023-06-09 17:00
Hi @oscarfossey, happy you find this project useful.
You should be able to run all the models using 8gb vram. I tested with the H model which is the biggest one and it uses <4gb vram.

Do you run inference using `inference.py`?  
can you paste the command you use to run inference and the error you get?  
When you run the models with torch it uses the GPU correctly?
Can you paste your versions of `torch` `nvidia-tensorrt` `onnxruntime-gpu`?

**Comment by oscarfossey** [comment] 2023-06-12 10:52
I use inference.py this way:

**Pytorch:**
`python src/inference.py --input=video.mp4  --output-path=output' model='vitpose-25-b.pth' --yolo-size=320 --save-img --model-name='b'`
Result: :heavy_check_mark:  GPU usage 1836/8192 MiB


**TensorRT:**
`python src/inference.py --input=video.mp4  --output-path=output' model='vitpose-25-b.engine' --yolo-size=320 --save-img --model-name='b'`
Result: :heavy_multiplication_x: : 
```
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Using cache found in /home/oscar/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-6-9 Python-3.10.11 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7982MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
Erreur de segmentation (core dumped)
```

**ONNX:**
`python src/inference.py --input=video.mp4  --output-path=output' model='vitpose-25-b.onnx' --yolo-size=320 --save-img --model-name='b'`
Result: :heavy_multiplication_x: : 
```
OpenCV: FFMPEG: tag 0x47504a4d/'MJPG' is not supported with codec id 7 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Using cache found in /home/oscar/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-6-9 Python-3.10.11 torch-2.0.1+cu117 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 7982MiB)

Fusing layers... 
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape... 
>>> Model loaded: /home/oscar/Workspace/External_repo/easy_ViTPose/vitpose-25-b.onnx
>>> Running inference on /home/oscar/Workspace/Data/camera_benchmark/videos/static.mp4
  0%|                                                                                                                                       | 0/120 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/oscar/Workspace/External_repo/easy_ViTPose/src/inference.py", line 340, in <module>
    frame_keypoints = model.inference(img)
  File "/home/oscar/Workspace/External_repo/easy_ViTPose/src/inference.py", line 131, in inference
    results = self.yolo(img, size=self.yolo_size)
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/oscar/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 705, in forward
    y = self.model(x, augment=augment)  # forward
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oscar/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 515, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oscar/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/oscar/.cache/torch/hub/ultralytics_yolov5_master/models/yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oscar/.cache/torch/hub/ultralytics_yolov5_master/models/common.py", line 59, in forward_fuse
    return self.act(self.conv(x))
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/oscar/anaconda3/envs/easy_vitpose/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```

- nvidia-tensorrt           99.0.0
- tensorrt                  8.6.1                    
- tensorrt-bindings         8.6.1                  
- tensorrt-libs             8.6.1   
- onnx                      1.14.0                  
- onnxruntime-gpu           1.15.0

**Comment by JunkyByte** [comment] 2023-06-12 12:01
Hello, I suggest you try one of the following:

- install the versions recommended in the `requirements.txt` and rerun with the provided onnx/trt models.

- inside `src/` there are two jupyter notebooks you can use to generate the onnx and trt models by yourself. If the problem is related to incompatibilities between versions generating your own might work.

**Comment by oscarfossey** [comment] 2023-06-12 12:28
I'll do that, thanks!

**Comment by JunkyByte** [comment] 2023-07-13 09:43
Closing, feel free to reopen this if you need further help

**Closed by JunkyByte** 2023-07-13 09:43 UTC
